// <auto-generated />
namespace anntgc00492University.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class KhoiTaoDuLieuAccountVoi2TruongMoi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KhoiTaoDuLieuAccountVoi2TruongMoi));
        
        string IMigrationMetadata.Id
        {
            get { return "201610020948422_KhoiTaoDuLieuAccountVoi2TruongMoi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
