// <auto-generated />
namespace Anntgc00492University.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChinhSuaCourseVaInstructor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChinhSuaCourseVaInstructor));
        
        string IMigrationMetadata.Id
        {
            get { return "201610041315108_ChinhSuaCourseVaInstructor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
